site_name: Pinta Pals
nav:
  - Home: index.md
  - First Steps:
    - Getting Started: start.md
    - General Overview: overview.md
    - Basic Concepts: concept.md
  - Quick Start: 
    - Setting Up Workspace: setup.md
    - Tutorial: tutorial.md
  - Image Layers:
    - Creating Layers: layers.md
    - Edit Layers: edit.md
    - Remove Layers: remove_layers.md
  - Selecting Objects:
    - Magic Wand: wand.md
    - Ellipse: ellipse.md
    - Lasso: lasso.md
    - Rectangle: rectangle.md
  - Illustrating:
    - Choose Pencil and Brush: choose.md
    - Creating Simple Objects: objects.md
    - Coloring: coloring.md
    - Removing Items: remove_items.md
  - Text Management:
    - Choose Font & Size: text.md
    - Text Style: style.md
    - Insert Text: insert.md
    - Remove Text: remove_text.md
  - Image Transformations:
    - Rotate: rotate.md
    - Flip: flip.md
    - Resize: resize.md
    - Crop and Straighten: crop.md
    - Adjust Canvas Size: adjust.md
    - Move: move.md
  - Image Enhancements:
    - Improving Colors: colors.md
    - Image Effects: effects.md
    - Filtering: filter.md
  - Image Repair & Restoration:
    - Reduce Red-Eye: redeye.md
    - Noise Reduction: noise.md
    - Remove Objects from Photos: remove_photos.md
    - Clone Stamp Tool: clone.md
  - Exporting Project:
    - Save Project: save.md
    - Print Project: print.md
  - Shortcuts: shortcuts.md
  - Glossary: glossary.md
  - Test: test.md
theme: 
  name: readthedocs