site_name: Pinta Pals
nav:
  - Home: index.md
  - First Steps:
    - 'Getting Started': start.md
    - 'Pinta Overview': overview.md
    - 'Basic Concepts': concept.md
  - Quick Start: 
    - 'Setting Up New Project': setup.md
    - 'Project Tutorial': tutorial.md
  - Layering on Images:
    - 'Add & Remove Images': images.md
    - 'Creating Layers': layers.md
    - 'Edit Layers': edit_layers.md
    - 'Remove Layers': remove_layers.md
  - Modifier Tools:
    - 'Selection': select.md
    - 'Zooming': zoom.md
    - 'Paintbrush': paintbrush.md
    - 'Pencil': pencil.md
    - 'Inking': ink.md
    - 'Eraser': erase.md
    - 'Clone Stamp': clone.md
    - 'Colour Picker': picker.md
    - 'Colour Palette': palette.md
    - 'Creating Shapes': shapes.md
    - 'Text Management': text.md
  - Image Enhancement: 
    - 'Sepia Filter': sepia.md
    - 'Black and White Filter': bw.md
    - 'Blurring Image': blur.md
    - 'Image Distortion': distort.md
    - 'Photo Red-Eye Reduction': redeye.md
    - 'Image Noise Reduction': noise.md
    - 'Posterize': posterize.md
    - 'Gradient': gradient.md
  - Colour Level Management: 
    - 'Auto Level': auto.md
    - 'Manual Level': manual.md
  - Exporting Project:
    - 'Save': save.md
    - 'Print': print.md
  - Appendix:
    - 'Shortcuts': shortcuts.md
    - 'Glossary': glossary.md
    - 'Test': test.md
theme: 
  name: readthedocs
  highlightjs: true
  hljs_style: zenburn
  nav_style: dark
