site_name: Pinta Pals
nav:
  - Home: index.md
  - First Steps:
    - 'General Overview': overview.md
    - 'Getting Started': start.md
  - Tutorial: tutorial.md
  - Layering on Images:
    - 'Add & Remove Images': images.md
    - 'Add & View Layers': layers.md
    - 'Edit Layers': edit_layers.md
    - 'Remove Layers': remove_layers.md
  - Modifier Tools:
    - 'Selection': select.md
    - 'Zooming': zoom.md
    - 'Paintbrush': paintbrush.md
    - 'Pencil': pencil.md
    - 'Inking': ink.md
    - 'Eraser': erase.md
    - 'Clone Stamp': clone.md
    - 'Colour Picker': picker.md
    - 'Colour Palette': palette.md
    - 'Creating Shapes': shapes.md
    - 'Text Management': text.md
  - Image Enchancement: 
    - 'Sepia': sepia.md
    - 'Black and White': bw.md
    - 'Blur': blur.md
    - 'Distort': distort.md
    - 'Red-Eye Reduction': redeye.md
    - 'Noise Reduction': noise.md
    - 'Posterize': posterize.md
    - 'Gradient': gradient.md
  - Colour Level Management: 
    - 'Auto Level': auto.md
    - 'Manual Level': manual.md
  - Save Project: save.md
  - Print Project: print.md
  - Shortcuts: shortcuts.md
  - Glossary: glossary.md
  - Test: test.md
theme: readthedocs
