site_name: Pinta Pals
nav:
  - Home: index.md
  - First Steps:
    - 'Getting Started': start.md
    - 'Pinta Overview': overview.md
    - 'Basic Concepts': concept.md
  - Quick Start: 
    - 'Setting Up New Project': setup.md
    - 'Project Tutorial': tutorial.md
  - Layering on Images:
    - 'Introduction to Layered Images': images.md
    - 'Creating Layers': layers.md
    - 'Edit Layers': edit_layers.md
    - 'Remove Layers': remove_layers.md
  - Creating with Pinta:
    - 'Decorating': 
      - 'Introduction to Decorations': decorate.md
      - 'Customize Paintbrush': paintbrush.md
      - 'Using Pencil': pencil.md
      - 'Inking': ink.md
      - 'Erasing': erase.md
      - 'Clone Stamping': clone.md
      - 'Creating Shapes': shapes.md
      - 'Drawing Lines': lines.md
      - 'Text Management': text.md
    - 'Modifying': 
      - 'Selection': select.md
      - 'Zooming': zoom.md
      - 'Colour Picker': picker.md
      - 'Colour Palette': palette.md
  - Enhancing Images: 
    - 'Enhancement Introduction': enchance.md
    - 'Improving Colours': 
      - 'Introduction to Colour Improvement': colours.md
      - 'Sepia Filter': sepia.md
      - 'Black and White Filter': bw.md
      - 'Posterize': posterize.md
      - 'Gradient': gradient.md
      - 'Auto Level': auto.md
      - 'Manual Level': manual.md
    - 'Adjusting Sharpness': 
      - 'Blurring Image': blur.md
      - 'Image Noise Reduction': noise.md
    - 'Removing Impurities': 
      - Image Distortion: distort.md
      - Photo Red-Eye Reduction: redeye.md
  - Exporting Project:
    - 'Save Image Project': save.md
    - 'Print Final Image': print.md
  - Appendix:
    - 'Shortcuts': shortcuts.md
    - 'Glossary': glossary.md
    - 'Test': test.md
theme: 
  name: readthedocs
  highlightjs: true
  hljs_style: zenburn
  extra_css: css/extra.css